/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CommandCentreRouteImport } from './routes/command-centre'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as WorkRouteImport } from './routes/work'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as CasesIndexRouteImport } from './routes/cases/index'
import { Route as CasesSlugRouteImport } from './routes/cases/$slug'
import { Route as DevelopmentIndexRouteImport } from './routes/development/index'
import { Route as DevelopmentSlugRouteImport } from './routes/development/$slug'
import { Route as IndustriesIndexRouteImport } from './routes/industries/index'
import { Route as IndustriesSlugRouteImport } from './routes/industries/$slug'
import { Route as SeoServicesIndexRouteImport } from './routes/seo-services/index'
import { Route as SeoServicesSlugRouteImport } from './routes/seo-services/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCentreRoute = CommandCentreRouteImport.update({
  id: '/command-centre',
  path: '/command-centre',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesIndexRoute = CasesIndexRouteImport.update({
  id: '/cases/',
  path: '/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesSlugRoute = CasesSlugRouteImport.update({
  id: '/cases/$slug',
  path: '/cases/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentIndexRoute = DevelopmentIndexRouteImport.update({
  id: '/development/',
  path: '/development/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentSlugRoute = DevelopmentSlugRouteImport.update({
  id: '/development/$slug',
  path: '/development/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoServicesIndexRoute = SeoServicesIndexRouteImport.update({
  id: '/seo-services/',
  path: '/seo-services/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoServicesSlugRoute = SeoServicesSlugRouteImport.update({
  id: '/seo-services/$slug',
  path: '/seo-services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/command-centre': typeof CommandCentreRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/studio': typeof StudioRoute
  '/work': typeof WorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/development/$slug': typeof DevelopmentSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/seo-services/$slug': typeof SeoServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/development/': typeof DevelopmentIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/seo-services/': typeof SeoServicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/command-centre': typeof CommandCentreRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/studio': typeof StudioRoute
  '/work': typeof WorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/development/$slug': typeof DevelopmentSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/seo-services/$slug': typeof SeoServicesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/cases': typeof CasesIndexRoute
  '/development': typeof DevelopmentIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/seo-services': typeof SeoServicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/command-centre': typeof CommandCentreRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/studio': typeof StudioRoute
  '/work': typeof WorkRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/development/$slug': typeof DevelopmentSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/seo-services/$slug': typeof SeoServicesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/cases/': typeof CasesIndexRoute
  '/development/': typeof DevelopmentIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/seo-services/': typeof SeoServicesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/command-centre'
    | '/contact'
    | '/login'
    | '/studio'
    | '/work'
    | '/blog/$slug'
    | '/cases/$slug'
    | '/development/$slug'
    | '/industries/$slug'
    | '/seo-services/$slug'
    | '/blog/'
    | '/cases/'
    | '/development/'
    | '/industries/'
    | '/seo-services/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/command-centre'
    | '/contact'
    | '/login'
    | '/studio'
    | '/work'
    | '/blog/$slug'
    | '/cases/$slug'
    | '/development/$slug'
    | '/industries/$slug'
    | '/seo-services/$slug'
    | '/blog'
    | '/cases'
    | '/development'
    | '/industries'
    | '/seo-services'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/command-centre'
    | '/contact'
    | '/login'
    | '/studio'
    | '/work'
    | '/blog/$slug'
    | '/cases/$slug'
    | '/development/$slug'
    | '/industries/$slug'
    | '/seo-services/$slug'
    | '/blog/'
    | '/cases/'
    | '/development/'
    | '/industries/'
    | '/seo-services/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommandCentreRoute: typeof CommandCentreRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  StudioRoute: typeof StudioRoute
  WorkRoute: typeof WorkRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CasesSlugRoute: typeof CasesSlugRoute
  DevelopmentSlugRoute: typeof DevelopmentSlugRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  SeoServicesSlugRoute: typeof SeoServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CasesIndexRoute: typeof CasesIndexRoute
  DevelopmentIndexRoute: typeof DevelopmentIndexRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  SeoServicesIndexRoute: typeof SeoServicesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-centre': {
      id: '/command-centre'
      path: '/command-centre'
      fullPath: '/command-centre'
      preLoaderRoute: typeof CommandCentreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/': {
      id: '/cases/'
      path: '/cases'
      fullPath: '/cases/'
      preLoaderRoute: typeof CasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$slug': {
      id: '/cases/$slug'
      path: '/cases/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof CasesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development/': {
      id: '/development/'
      path: '/development'
      fullPath: '/development/'
      preLoaderRoute: typeof DevelopmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development/$slug': {
      id: '/development/$slug'
      path: '/development/$slug'
      fullPath: '/development/$slug'
      preLoaderRoute: typeof DevelopmentSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-services/': {
      id: '/seo-services/'
      path: '/seo-services'
      fullPath: '/seo-services/'
      preLoaderRoute: typeof SeoServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo-services/$slug': {
      id: '/seo-services/$slug'
      path: '/seo-services/$slug'
      fullPath: '/seo-services/$slug'
      preLoaderRoute: typeof SeoServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommandCentreRoute: CommandCentreRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  StudioRoute: StudioRoute,
  WorkRoute: WorkRoute,
  BlogSlugRoute: BlogSlugRoute,
  CasesSlugRoute: CasesSlugRoute,
  DevelopmentSlugRoute: DevelopmentSlugRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  SeoServicesSlugRoute: SeoServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  CasesIndexRoute: CasesIndexRoute,
  DevelopmentIndexRoute: DevelopmentIndexRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  SeoServicesIndexRoute: SeoServicesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
